### ISSUE TITLE
Add babashka support

### ISSUE THREAD

**Issue by jjttjj** [exoscale/interceptor#9]
Hi, thanks for this library.

Wondering if you're interested in adding Babashka support?

I believe (and have tested a bit) that this can be achieved with a single change adding a reader conditional Sci's var type, replacing these lines:
https://github.com/exoscale/interceptor/blob/fe9832be8d7d2d9bc5c0cc743f7495d7750d4920/src/exoscale/interceptor/impl.cljc#L24-L26
With this
```clojure
#?(:bb sci.lang.Var
   :clj clojure.lang.Var
   :cljs clojure.lang.Var)
  (interceptor [v]
    (p/interceptor (deref v)))
```
(Babashka's reader conditionals are explained here: https://book.babashka.org/#_reader_conditionals)

I could provide a PR if you prefer.

Edit: I have noticed this fix only works with a relatively recent version of babashka. It works with v0.9.160 but not with v0.8.2. I could investigate this further and possibly find a more generally compatible solution if you're interested in adding the support

**Comment by mpenet** [comment]
Sure! That'd be a great addition.

**Comment by mpenet** [comment]
Feel free to test https://github.com/exoscale/interceptor/pull/11. Hopefully that should be enough.
